name: Lint Keypad Controller

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch
on:
  pull_request:
    branches:
      - master
      - development
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # # pip install wheel
    # sudo apt-get install libwxgtk3.0-gtk3-dev
    # #sudo apt-get install libgtk-3-dev
    # sudo apt-get install build-essential
    # sudo apt-get install tk-dev
    - name: Install Requirements
      run: |
        sudo apt-get update -q && sudo apt-get install
        # sudo apt-get install python-wxgtk3.0
        python -m pip install --upgrade pip
        sudo apt-get install -y libgtk2.0-dev libgtk-3-dev \
	                   libjpeg-dev libtiff-dev \
	                   libsdl1.2-dev libgstreamer-plugins-base0.10-dev \
	                   libnotify-dev freeglut3 freeglut3-dev libsm-dev \
	                   libwebkitgtk-dev libwebkitgtk-3.0-dev
        # pip install wheel
        pip install jsonschema
        pip install pylint
        pip install twisted
        pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04 wxPython
    - name: Run Pylint
      run: |
        cd src
        export PYTHONPATH=`pwd`/keypad_controller
        python ../pipelines/lint.py --path keypad_controller --threshold 10
